package com.example.desenrolaopapo

val primeiroEncontro = listOf(
    "Como você descreveria sua rotina ideal?",
    "O que te faz acordar animado(a) pela manhã?",
    "Qual parte do seu dia você mais gosta?",
    "Você é mais de planejar ou de deixar as coisas acontecerem?",
    "Tem algum hábito que mudou sua vida recentemente?",
    "Como é sua relação com sua família?",
    "Qual foi a maior lição que seus pais te ensinaram?",
    "Você tem algum costume de família que carrega até hoje?",
    "Como era você na adolescência?",
    "Qual memória da sua infância você mais guarda com carinho?",
    "O que te levou a escolher sua profissão/área de estudo?",
    "Se pudesse mudar algo no seu trabalho atual, o que seria?",
    "O que você aprendeu de mais valioso em seus empregos ou estudos?",
    "Tem algum projeto profissional que sonha em realizar?",
    "Como você lida com desafios no trabalho?",
    "O que você considera mais importante em um relacionamento?",
    "Qual sua opinião sobre equilíbrio entre vida pessoal e profissional?",
    "O que você não tolera em uma amizade ou relacionamento?",
    "Qual foi a situação que mais te fez crescer como pessoa?",
    "Como você define 'sucesso' para você?",
    "Tem algum hobby que gostaria de transformar em algo maior?",
    "O que você faz para relaxar depois de um dia cansativo?",
    "Qual atividade te faz perder a noção do tempo?",
    "Tem algum lugar que visita sempre para recarregar as energias?",
    "Qual foi a última coisa nova que você experimentou e gostou?",
    "Qual é um objetivo que parece pequeno, mas te deixaria muito feliz?",
    "Tem algum sonho de infância que ainda quer realizar?",
    "O que você priorizaria se tivesse um ano livre e sem preocupações?",
    "Como você imagina sua vida daqui a 5 anos?",
    "Qual é o maior desafio que você quer superar?",
    "O que te faz sentir realmente amado(a) ou valorizado(a)?",
    "Qual foi a coisa mais importante que aprendeu em relacionamentos passados?",
    "Como você lida com conflitos em relacionamentos?",
    "O que você acha essencial para construir confiança com alguém?",
    "Qual sua linguagem do amor principal (toque, palavras, tempo de qualidade, etc.)?",
    "Tem algum livro/filme/série que mudou sua perspectiva sobre algo?",
    "Qual artista ou figura pública você admira e por quê?",
    "Como você forma suas opiniões sobre temas polêmicos?",
    "Qual assunto você poderia conversar por horas?",
    "Tem alguma crença ou valor que ninguém consegue te fazer mudar?",
    "Qual foi o momento mais difícil da sua vida e como lidou com ele?",
    "Como você reage quando as coisas não saem como planejado?",
    "O que te ajuda a seguir em frente nos dias mais difíceis?",
    "Tem algum medo que está trabalhando para superar?",
    "O que você diria para sua versão de 10 anos atrás?",
    "Se pudesse voltar no tempo, qual conselho se daria?",
    "O que você quer que as pessoas lembrem de você?",
    "Tem algo que está adiando há muito tempo e gostaria de fazer?",
    "Como você espera estar daqui a 20 anos?",
    "Qual legado gostaria de deixar?",
    "O que te faz sentir verdadeiramente realizado(a)?",
    "Qual experiência te tornou mais resiliente?",
    "Como você define 'amor' para você?",
    "O que você aprendeu sobre si mesmo(a) nos últimos anos?",
    "Qual é a coisa mais importante que você busca em uma parceria?",
    "Qual foi a decisão mais difícil que já tomou?",
    "Como você lida com críticas?",
    "O que você faz quando se sente sobrecarregado(a)?",
    "Qual foi a última vez que saiu da sua zona de conforto?",
    "Como você demonstra afeto pelas pessoas que ama?",
    "O que você acha que é sua maior qualidade?",
    "Qual foi a conversa que mais marcou sua vida?",
    "Como você descreveria sua personalidade em três palavras?",
    "O que você mais valoriza em uma amizade?",
    "Qual foi a maior surpresa que a vida te deu?",
    "Como você pratica autocuidado?",
    "O que você acha que é fundamental para uma vida feliz?",
    "Qual foi o conselho mais sábio que já recebeu?",
    "Como você mantém sua mente aberta para novas perspectivas?",
    "O que você faz quando precisa tomar uma decisão importante?",
    "Qual foi a fase mais transformadora da sua vida?",
    "Como você reage a mudanças inesperadas?",
    "O que você acha que é sua maior fraqueza?",
    "Qual foi a experiência que mais te ensinou sobre empatia?",
    "Como você define 'casa' para você?",
    "O que você faz quando está se sentindo perdido(a)?",
    "Qual foi o momento em que você se sentiu mais orgulhoso de si mesmo?",
    "Como você equilibra suas necessidades com as dos outros?",
    "O que você acha que é a chave para uma comunicação saudável?",
    "Qual foi a lição mais dolorosa que você aprendeu?",
    "Como você sabe quando pode confiar em alguém?",
    "O que você faz para manter sua saúde mental em dia?",
    "Qual foi a vez que você mais se surpreendeu com você mesmo?",
    "Como você lida com a solidão?",
    "O que você acha que é essencial para um relacionamento duradouro?",
    "Qual foi a coisa mais corajosa que você já fez?",
    "Como você mantém viva sua curiosidade sobre o mundo?",
    "O que você faz quando sente que está estagnado(a)?",
    "Qual foi a experiência que mais te ensinou sobre perdão?",
    "Como você sabe que está no caminho certo na vida?",
    "O que você faz para cultivar gratidão no seu dia a dia?",
    "Qual foi a vez que você mais sentiu que pertencia a algum lugar?",
    "Como você lida com expectativas não realizadas?",
    "O que você acha que é a coisa mais importante a se ensinar para uma criança?",
    "Qual foi a decisão que mais te trouxe paz?",
    "Como você sabe quando é hora de deixar algo ir?",
    "O que você faz para se reconectar consigo mesmo quando se sente perdido?"
)

val redesSociais = listOf(
    "Vi que você postou sobre [assunto]. Como foi essa experiência?",
    "Esse lugar que você marcou no story é tão bom quanto parece?",
    "Você recomenda esse [filme/série] que você postou?",
    "Como você descobriu esse [lugar/comida] que mostrou?",
    "Qual foi a história por trás daquela foto incrível que você postou?",
    "Qual conta no Instagram/TikTok você mais recomenda seguir?",
    "Se você pudesse jantar com qualquer pessoa das redes sociais, quem seria?",
    "Qual foi o último post que salvou pra ver depois?",
    "Qual influencer você acha superestimado?",
    "Qual meme te define nessa semana?",
    "Qual rede social você acha que vai sumir nos próximos anos?",
    "O que você acha de stories que somem em 24h?",
    "Você prefere postar ou só consumir conteúdo?",
    "Qual a opinião mais polêmica que você tem sobre redes sociais?",
    "O que te faz seguir ou deixar de seguir alguém?",
    "Qual rede social você mais sente falta do jeito que era antigamente?",
    "Lembra de alguma trend antiga que deveria voltar?",
    "Qual foi seu primeiro perfil em rede social?",
    "Qual foi o post mais vergonhoso que você já deletou?",
    "O que você mais estranhou quando as redes sociais viraram parte da vida?",
    "Se você pudesse criar um filtro de Instagram, como seria?",
    "Se sua vida virasse um perfil temático, qual seria o tema?",
    "Qual famoso deveria ser cancelado por algo bobo?",
    "Se você ganhasse R$10.000 pra ficar 1 mês offline, topava?",
    "Se existisse um botão de 'despostar', você usaria muito?",
    "O que te faz dar like em um story?",
    "Qual a melhor reação pra mensagem que você não quer responder?",
    "O que você acha de gente que responde story com '😍' genérico?",
    "Qual a pior tática de flerte que já viram nas DMs?",
    "O que te faz bloquear alguém sem pensar duas vezes?",
    "Qual trend você nunca entendeu?",
    "Qual assunto merecia mais atenção nas redes?",
    "Qual foi o post mais útil que você viu esse mês?",
    "Você já caiu em algum golpe/fake news das redes?",
    "Qual nicho de conteúdo você mais consome?",
    "Qual seu vício secreto de rede social?",
    "Já stalkeou alguém e descobriu algo inesperado?",
    "Qual foi a coisa mais vergonhosa que já fez por likes?",
    "Já deixou de responder alguém por pura preguiça?",
    "Qual foi o maior vacilo que já deu online?",
    "Você acha que as redes vão substituir interações reais?",
    "Toparia viver num metaverso estilo Black Mirror?",
    "O que você acha de IA criando conteúdo como se fosse humano?",
    "Como você imagina as redes sociais daqui a 10 anos?",
    "Qual rede social será a próxima a dominar o mundo?",
    "Me indica três perfis que todo mundo deveria seguir!",
    "Qual foi a DM mais inesperada que você já recebeu?",
    "Se seu feed fosse um gênero musical, qual seria?",
    "Qual a pior moda que já seguiu nas redes?",
    "O que você acha de gente que posta 'indireta'?",
    "Você é do time que posta tudo ou do time que some das redes?",
    "O que te faz tirar print de uma conversa?",
    "Qual foi a discussão mais desnecessária que já viu online?",
    "Já se arrependeu de algo que postou no calor do momento?",
    "O que te faz apagar um post depois de publicar?",
    "Qual rede social tem a melhor algoritmo na sua opinião?",
    "Você prefere TikTok ou Reels? Por quê?",
    "Qual rede social tem a pior comunidade?",
    "Instagram com ou sem likes visíveis?",
    "Twitter (X) antes ou depois do Elon?",
    "Qual dica você daria pra quem está começando nas redes?",
    "Já teve algum problema sério por causa de rede social?",
    "O que você acha de expor relacionamentos online?",
    "Até que ponto você acha seguro compartilhar da vida nas redes?",
    "Qual informação pessoal você nunca postaria?",
    "Qual a pior trend que já viu nas redes?",
    "Se seu último search virasse um post, você estaria em apuros?",
    "Qual celebridade tem o pior feed de todos?",
    "Qual foi o cancelamento mais sem noção que já viu?",
    "O que você acha de gente que posta café da manhã todo dia?",
    "Qual foi a interação mais legal que já teve por aqui?",
    "O que te faz continuar usando essa rede social?",
    "Se pudesse deletar uma rede social pra sempre, qual seria?",
    "Qual pessoa das redes sociais te inspira de verdade?",
    "O que você acha que falta nas redes sociais hoje?"
)

val fazerAmizade = listOf(
    "Qual foi a coisa mais aleatória que te aconteceu essa semana?",
    "Se você pudesse ter um talento instantâneo, qual seria?",
    "Qual lugar te dá a sensação de 'estar em casa', mesmo não sendo sua casa?",
    "O que você faz quando está sozinho(a) e entediado(a)?",
    "Qual foi a última coisa que te deixou genuinamente animado(a)?",
    "Qual foi sua fase mais estranha na adolescência?",
    "Qual foi a coisa mais legal que já te aconteceu por acaso?",
    "Qual foi seu primeiro emprego e o que você aprendeu com ele?",
    "Você tem alguma história familiar que todo mundo sempre conta?",
    "Qual foi a maior loucura que você já fez por um amigo?",
    "Qual música você ouve quando precisa melhorar seu humor?",
    "Se você pudesse comer apenas uma comida pelo resto da vida, qual seria?",
    "Qual filme/série você já assistiu mais vezes?",
    "Que atividade te faz perder a noção do tempo?",
    "Qual cheiro te traz boas memórias?",
    "O que você mais valoriza em uma amizade?",
    "Qual foi a lição mais difícil que você já aprendeu?",
    "Como você sabe que pode confiar em alguém?",
    "O que te faz cortar relações com alguém?",
    "Qual qualidade sua você acha que as pessoas não percebem de primeira?",
    "Como você costuma conhecer pessoas novas?",
    "Qual foi o lugar mais inesperado onde você fez um amigo?",
    "Você prefere planos em grupo ou encontros one-on-one?",
    "Qual foi a melhor festa/evento social que você já foi?",
    "Como você mantém contato com amigos que moram longe?",
    "Qual parte da sua rotina você não abre mão?",
    "Como é sua manhã ideal?",
    "O que você sempre faz antes de dormir?",
    "Qual pequeno luxo você se permite no dia a dia?",
    "O que você faz quando precisa recarregar as energias?",
    "Sobre qual assunto você mudou completamente de opinião?",
    "Qual conselho você daria para sua versão mais nova?",
    "O que você acha que é supervalorizado hoje em dia?",
    "Qual foi a conversa que mais te marcou na vida?",
    "O que você acha que é o segredo para uma boa conversa?",
    "Qual foi o momento mais bonito que você já presenciou?",
    "Já teve algum encontro aleatório que mudou seu dia?",
    "Qual foi a coisa mais corajosa que você já fez?",
    "Qual lugar te surpreendeu por ser completamente diferente do que você imaginava?",
    "Qual foi a maior coincidência que já aconteceu com você?",
    "Qual sonho seu parece pequeno, mas te deixaria muito feliz?",
    "Se dinheiro não fosse problema, como você passaria seus dias?",
    "Qual habilidade você gostaria de desenvolver?",
    "Como você imagina sua vida daqui a 10 anos?",
    "O que você gostaria de fazer antes de ficar velho(a)?",
    "Quando você se sentiu mais compreendido(a) por alguém?",
    "O que te faz sentir verdadeiramente realizado(a)?",
    "Como você lida com a solidão?",
    "Qual foi o momento que mais te fez crescer como pessoa?",
    "O que você aprendeu sobre si mesmo(a) nos últimos anos?",
    "Se você pudesse jantar com qualquer pessoa, viva ou morta, quem seria?",
    "Se sua vida fosse um filme, qual seria o título?",
    "Se você pudesse morar em qualquer lugar do mundo por um ano, onde seria?",
    "Se pudesse voltar no tempo com o conhecimento que tem hoje, o que mudaria?",
    "Se você tivesse que sumir por um mês, como explicaria seu sumiço depois?",
    "Qual foi o presente mais significativo que você já recebeu?",
    "Qual memória da infância te traz mais felicidade?",
    "Qual foi o momento mais orgulhoso da sua vida?",
    "Qual foi a maior demonstração de amor que você já presenciou?",
    "Qual foi a vez que você mais riu na vida?",
    "Como você descreveria sua personalidade em 3 palavras?",
    "Qual parte da sua personalidade você acha que as pessoas demoram a entender?",
    "O que te faz sair da sua zona de conforto?",
    "Como você reage quando as coisas não saem como planejado?",
    "O que você faz quando está se sentindo para baixo?",
    "Qual foi a coisa mais inútil que você já aprendeu?",
    "Se você fosse um personagem fictício, qual seria?",
    "Qual seria sua armadilha em um reality show?",
    "Qual seria seu superpoder mais inútil?",
    "Se animais pudessem falar, qual espécie seria a mais chata?",
    "O que você acha que faz alguém ser um bom amigo?",
    "Qual experiência você acha que todo mundo deveria ter na vida?",
    "O que você gostaria que mais pessoas entendessem sobre você?",
    "Como você sabe que encontrou uma amizade verdadeira?",
    "O que você mais aprecia nas pessoas que mantém por perto?"
)

val conhecerMelhor = listOf(
    "Como você descreveria sua essência em 3 palavras?",
    "Qual experiência te definiu como pessoa?",
    "O que ninguém consegue perceber sobre você de imediato?",
    "Qual é a contradição mais interessante na sua personalidade?",
    "Que parte da sua personalidade você menos mostra nas redes sociais?",
    "Como sua infância moldou quem você é hoje?",
    "Qual crença sobre vida você carrega que poucos compartilham?",
    "O que te faz sentir verdadeiramente vivo(a)?",
    "Qual é o seu 'eu autêntico' que poucos conhecem?",
    "Que máscara social você usa com mais frequência?",
    "Qual foi o momento que mais te transformou?",
    "Do que você mais se orgulha em sua jornada pessoal?",
    "Qual ferida emocional te ensinou mais?",
    "Como você reage quando se sente profundamente incompreendido(a)?",
    "Que parte de você você ainda está descobrindo?",
    "Quais são seus 3 princípios inegociáveis?",
    "Em que situação você quebraria seus próprios valores?",
    "O que você considera traição em qualquer tipo de relação?",
    "Como você define 'integridade' na prática?",
    "Qual preconceito seu você está trabalhando para superar?",
    "Que coisa socialmente aceita você acha moralmente errada?",
    "Quando você percebeu que tinha valores diferentes da sua família?",
    "Qual opinião sua já causou atrito por ser pouco popular?",
    "O que você absolutamente não tolera, mas a maioria ignora?",
    "Como você equilibra ambição pessoal com cuidado pelos outros?",
    "Qual lição você aprendeu da maneira mais difícil?",
    "O que você sabe que é verdade, mas não consegue provar?",
    "Como você reconhece amor verdadeiro?",
    "Qual foi sua maior lição sobre confiança?",
    "O que te faz sentir verdadeiramente seguro(a) em uma relação?",
    "Como você lida com a vulnerabilidade emocional?",
    "Qual padrão em relacionamentos você está tentando quebrar?",
    "Que necessidade emocional sua é mais difícil de expressar?",
    "Como você sabe quando é hora de deixar alguém ir?",
    "Qual foi o gesto mais significativo que já recebeu?",
    "O que você aprendeu sobre perdão que mudou sua perspectiva?",
    "Como você mantém sua identidade em relacionamentos íntimos?",
    "Qual medo seu mais atrapalha suas conexões?",
    "Que tipo de amor você ainda está aprendendo a receber?",
    "Como você reconstrói confiança depois de traída?",
    "O que ninguém nunca te perguntou, mas você gostaria de compartilhar?",
    "Qual é o seu maior desafio nos relacionamentos atualmente?",
    "Que experiência mudou radicalmente sua perspectiva sobre algo?",
    "Em que área da vida sua opinião mais evoluiu nos últimos anos?",
    "Qual sistema social você acha que precisa ser reinventado?",
    "Que verdade dura sobre a humanidade você teve que aceitar?",
    "Como você encontra propósito em meio ao caos do mundo?",
    "Que tradição moderna você acha que será obsoleta em 50 anos?",
    "Qual é o paradoxo humano que mais te fascina?",
    "Que problema global te deixa mais indignado(a)?",
    "O que você sabe que é impopular, mas precisa ser dito?",
    "Como você reconcilia esperança e realismo?",
    "Qual progresso da humanidade te dá mais esperança?",
    "Que aspecto da condição humana você acha subestimado?",
    "Como você define 'uma vida bem vivida'?",
    "Qual emoção você mais evita sentir e por quê?",
    "Que padrão negativo você está tentando quebrar?",
    "Como seu autodiálogo mais crítico soa?",
    "Qual defesa emocional você usa com mais frequência?",
    "Que parte de você você rejeitou no passado e agora aceita?",
    "Qual foi seu momento mais revelador em terapia (ou autoanálise)?",
    "Como você distingue intuição de medo?",
    "Qual verdade sobre si mesmo(a) você demorou para aceitar?",
    "O que seu eu criança mais precisa ouvir?",
    "Que mentira você contou para si mesmo(a) por muito tempo?",
    "Como você reconhece quando está se auto-sabotando?",
    "Qual aspecto do seu crescimento pessoal te surpreendeu?",
    "O que você está desaprendendo atualmente?",
    "Qual ferida emocional ainda precisa de cura?",
    "Como você pratica autocompaixão nos dias difíceis?",
    "Qual sonho secreto você nunca compartilhou?",
    "O que você mais temeria perder na vida?",
    "Qual risco emocional você ainda não teve coragem de tomar?",
    "Como você lida com o sentimento de não ser suficiente?",
    "Qual é seu maior medo sobre o futuro?",
    "Que parte da sua vida você gostaria de reescrever?",
    "O que te impede de ir atrás do que realmente quer?",
    "Qual é a dúvida existencial que mais te persegue?",
    "Como você imagina seu 'eu' mais pleno?",
    "O que você precisa abandonar para crescer?",
    "Qual é a pergunta sobre vida que mais te intriga?",
    "Como você define 'significado' na sua existência?",
    "O que a morte te ensinou sobre viver?",
    "Qual experiência te fez questionar tudo que acreditava?",
    "Como você reconcilia liberdade e responsabilidade?",
    "O que você sabe que é efêmero, mas valoriza profundamente?",
    "Qual é o paradoxo da vida que mais te toca?",
    "Como você encontra beleza no ordinário?",
    "O que te faz sentir parte de algo maior?",
    "Qual conselho você daria para a humanidade futura?",
    "O que essa conversa revelou sobre você que você não esperava?",
    "Qual pergunta você esperava que eu fizesse, mas não fiz?",
    "O que você está sentindo agora que não está dizendo?",
    "Qual camada sua nós ainda não exploramos?",
    "Como você se sente sendo verdadeiramente visto(a)?",
    "O que você gostaria que eu lembrasse sobre você?",
    "Qual parte de você você ainda está hesitante em compartilhar?",
    "O que você descobriu sobre mim que te surpreendeu?",
    "Como essa conversa mudou sua percepção sobre conexões?",
    "Qual verdade nós criamos juntos aqui hoje?"
)